name: 'test'
type: 'jenkins'
count: 10
template_id: 3
opennebula_user_id: 9
provision:
  - type: "script"
    path: "/root/provisioners/jenkins.sh"
jenkins: 'https://fake-ivy/jenkins'
jenkins_username: '${user}'
jenkins_password: '${password}'
credentials_id: '2dfc58d2-9d2e-49dd-849b-4eb1a4933e54'
private_key_path: '${id_rsa}'
